name: AWS CFN Response Checker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --pre --dev
    - name: Run behavioural tests
      run: |
        export AWS_DEFAULT_REGION=ap-southeast-2
        behave
    - name: Run unit tests
      run: pytest
